# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ke Blog
description: > # this means to ignore newlines until "baseurl:"
  A blog for KE.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keblog.me" # the base hostname & protocol for your site
timezone: America/New_York

# Plugins
gems: [jekyll-paginate]

# Paginate
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: rouge
